import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google"; 
import "../styles/globals.css";  
import {  TopHeader,Header } from "@/components/header";
import Footer from "@/components/footer";
import React from "react"
import Link from "next/link";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        
        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
